### ISSUE TITLE
DST: Option to make the grid match with the boat

### ISSUE THREAD

**Issue by ViktorYu234** [rezecib/Geometric-Placement#33]
My friends and I enjoy it to build our own boats in DST. To fit as many structures on it as possible, we're using your Geometric Placement mod. But sadly it only works as long as the boat didn't move yet, because the grid doesn't move with the boat at all, and as soon as the boat starts moving, the grid will stop to match with the boat itself or all the other structures on the boat. 

Could you please add one of the following options to make it possible placing structures geometrically on the boat even after the boat started moving?
- Add a button which can be pressed to make the grid match with the object your cursor points at, in the way that there'll appear a dot right where that object stands on. If you press the button while your cursor points at nothing, then the grid becomes normal again. (That would also help to place e.g. a perfectly hexagonal kitchen if the ice box has already been placed in square mode)
- If active and if the player stands on a platform (player:GetCurrentPlatform()), then the grid realigns itself to match the boat in the way that there's always a dot right in the center of the boat.

**Comment by rezecib** [comment]
Nice idea, I've had some thoughts in this direction (I've seen a request for being able to center the grid on the center of a tile before, for example). But it's definitely more game-breaking for boats given that they can move around. I'll see what I can do, although I don't find much time to work on my mods nowadays.
