### ISSUE TITLE
Don't hide the tilling grid immediately after unhovering a soil tile

### ISSUE THREAD

**Issue by Sworddragon** [rezecib/Geometric-Placement#44]
With Geometric Placement 3.0.10 when I experimented with farming some days ago I noticed something was really weird on retilling the random uprisings close to the soil tile edge after using the Garden Rigama Jig. On checking this now again I see what the issue is: Once the mouse cursor hovers out of any soil tile the tilling grid immediately closes. This kind of makes it a bit tricky moving initail uprisings that are close to the edge of the soil tile to a more inner position. And if somebody desires to have them exactly on the tile outline it becomes even more so.

I did compare this now with what the behavior is when hovering from 1 unit to another: The white outlined x sticks at the unit until the mouse cursor hovered halfway through the next unit. I think it makes sense if this behavior could also be applied to the edge of the soil tile where it meets a non-soil tile: The tilling grid could then only close once the mouse cursor hovered halfway away from the last unit. Eventually this should be done also the other way around: The tilling grid could already be shown once the mouse cursor gets half a unit close to the soil tile.

Edit: I just noticed that a similar issues applies to e.g. Planted Seeds and Garden Detritus - so eventually showing the tilling grid could be stabilized here too so it feels not that unstable on hovering with the mouse cursor.

**Comment by rezecib** [comment]
Difficult for similar reasons as https://github.com/rezecib/Geometric-Placement/issues/43#issuecomment-842774896
