### ISSUE TITLE
Showing units close to empty soil tile uprisings as tilleable

### ISSUE THREAD

**Issue by Sworddragon** [rezecib/Geometric-Placement#45]
Similar to issue #44 when I did some experiments with farming one thing that made it a bit tricky was that units close to empty uprisings are shown as non-tilleable. This conflicts a bit with that only 2 out of the 4 tile borders where the tile outline is shown have their units tilleable. Normally this would be easily distinguishable since Geometric Placement shows those units as tilleable and non-tilleable but since (random) empty uprisings are there it becomes hard to tell which borders are which.

A fix for this would be to simply show units close to empty uprisings as tilleable. I'm also a bit curious why they are shown as non-tilleable - I guess it might be simply a bug.

**Comment by rezecib** [comment]
This was intentional. Tilling has some weird interactions where you can till in places that destroy existing tilled soil. I wanted to show the nearest points that you could till without destroying existing ones, for example to more easily do a grid.
