### ISSUE TITLE
screens/optionsscreen moved to screens/redux/optionsscreen

### ISSUE THREAD

**Issue by chrisjwei** [rezecib/Geometric-Placement#5]
Hi, big fan of your mods. Geometric placement is crashing with the newest update:
https://forums.kleientertainment.com/topic/91042-game-update-269472/?do=findComment&comment=1037532

I modified my local version of this mod to use "screens/redux/optionsscreen" and it seems to work

**Comment by rezecib** [comment]
`optionsscreen` and `redux/optionsscreen` are actually quite different, I initially tried updating to point to redux but it crashed immediately. I don't really have time right now to update the code that was working with it (it was supporting a nicer system for setting the mod keybinds and providing an in-game way of setting Show Nearest Tile, but these are... luxury features that aren't really necessary if you get the options set the way you want to).

I updated the mod to just comment out that code until I get a chance to update it to work properly with the redux UI.
